# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_traffic_intersection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traffic',
            name='is_params',
            field=models.BooleanField(default=False),
        ),
    ]
