# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181114_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='appr1_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traffic',
            name='appr2_name',
            field=models.CharField(default=datetime.datetime(2018, 11, 14, 4, 13, 17, 347000, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
    ]
