# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181128_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='trafficlightinfo',
            fields=[
                ('intersection_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('appr_id', models.CharField(max_length=30)),
                ('appr_name', models.CharField(max_length=80)),
                ('tlgreen', models.IntegerField()),
                ('tlyellow', models.IntegerField()),
                ('tlred', models.IntegerField()),
            ],
        ),
    ]
