# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_trafficlightinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlightinfo',
            name='appr_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficlightinfo',
            name='intersection_id',
            field=models.CharField(max_length=30),
        ),
    ]
