# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-09 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181205_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='phase_one',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='phase_two',
        ),
    ]
