# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traffic',
        ),
    ]
