# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181105_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traffic',
        ),
    ]
