# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_traffic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic',
            old_name='phase_true',
            new_name='intersection_id',
        ),
        migrations.AddField(
            model_name='traffic',
            name='phase_two',
            field=models.CharField(default=datetime.datetime(2018, 11, 5, 9, 12, 24, 415000, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
