# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181105_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='intersection_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
