# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_one', models.CharField(max_length=30)),
                ('phase_true', models.CharField(max_length=30)),
            ],
        ),
    ]
