# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181105_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='id',
        ),
        migrations.AlterField(
            model_name='traffic',
            name='intersection_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
