# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181111_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='phase_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='phase_two',
            field=models.IntegerField(),
        ),
    ]
