# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181114_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection_id', models.CharField(max_length=30)),
                ('appr_name', models.CharField(max_length=80)),
                ('vtb', models.FloatField()),
                ('vhc_come', models.IntegerField()),
                ('vhc_out', models.IntegerField()),
            ],
        ),
    ]
