# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-19 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_infointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='infointer',
            name='appr_id',
            field=models.CharField(default=datetime.datetime(2018, 11, 19, 7, 56, 12, 644000, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
